language: node_js
sudo: false
node_js:
  - "0.12"
before_install:
  - npm install -g Financial-Times/origami-build-tools#node12
  - origami-build-tools install
script:
  - origami-build-tools test
  - origami-build-tools verify
